name: Test Determine Image Tags

on:
  push:
    branches:
      - main
      - feature/*
  release:
    types:
      - created

permissions:
  contents: read

jobs:
  test-determine-image-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up test inputs
        run: |
          echo "VERSION=v0.0.5" >> $GITHUB_ENV
          echo "BASE_IMAGE=example/test-image" >> $GITHUB_ENV

      - name: Run Determine Image Tags action
        uses: ./.github/actions/determine-tags
        id: image_tags
        with:
          custom_tag: ""
          version: ${{ env.VERSION }}
          base_image: ${{ env.BASE_IMAGE }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Display computed image tags
        run: |
          echo "Computed tags: ${{ steps.image_tags.outputs.image_tags }}"
